### ISSUE TITLE
Add option to return an error when an unknown key is encountered

### ISSUE THREAD

**Issue by andrewkroh** [elastic/go-ucfg#10]
When unmarshaling/unpacking the config data, I would like to be able to set an option that will cause an error to be returned when a key is encountered that does not exist in the provided struct.

It would be great if the error message provided helpful information like the supported keys. This is the error message that Winlogbeat creates now by checking at the keys in the raw config.

`2016/03/23 05:07:14.639896 beat.go:128: CRIT Start error: setup returned an error: Failed to create new event log. 1 error: Invalid event log key 'invalid' found. Valid keys are api, event_id, fields, fields_under_root, ignore_older, include_xml, level, name, provider, tags`

And also:

`1 error: Invalid top-level key 'other' found. Valid keys are logging, output, shipper, winlogbeat`

**Comment by urso** [comment]
At which place in API would you like to apply the option? `Unpack` ? Some configurations might be used by multiple modules, each reading only a subset of options. In this case #6 seems more appropriate (1. unpack, 2. check all fields being accessed).

**Comment by urso** [comment]
We would like some form of configuration validation in general. But this issue only catches a small subset of potential validation issues. Closing.
