### ISSUE TITLE
Update uuid dependency

### ISSUE THREAD

**Issue by tsg** [elastic/go-ucfg#102]
Our UUID library, github.com/satori/go.uuid, has changed the signature of the interface for the `NewV4` function. This still works in beats because we vendor v1.0.0. We should update our usage to be able to use newer versions of this lib.

**Comment by urso** [comment]
Which version did you try to update to? v1.2.0 of go.uuid still uses old interface it seems: https://github.com/satori/go.uuid/blob/v1.2.0/generator.go#L64

Only [master](https://github.com/satori/go.uuid/blob/master/generator.go#L68) has been changed to introduce an error return.

**Comment by ph** [comment]
@urso I can confirm this too, I was about to make the PR but realized that the update didn't break any tests.

**Comment by ph** [comment]
Adding the commit with the change, our current code in _types.go_ will panic if we run out of entropy, I guess we will want to keep the same behavior when we need to do the update.

https://github.com/satori/go.uuid/commit/0ef6afb2f6cdd6cdaeee3885a95099c63f18fc8c

**Comment by urso** [comment]
For now I'd say yes, panic on error.

**Comment by urso** [comment]
UUIDs are not used by go-ucfg anymore. Closing.
