### ISSUE TITLE
Environment variable expansion in string context triggers JSON parser

### ISSUE THREAD

**Issue by adriansr** [elastic/go-ucfg#132]
When an environment variable is expanded inside a string:
```yaml
field: "${MY_VAR}"
```

The parser will in turn try to parse the variable contents as if they were JSON values. For example when `MY_VAR` is `{user}`, the parser will complain that the input is malformed:

```
expected ':' when parsing '{user' accessing 'field'
```

which doesn't happen when the same value is hardcoded:

```
field "{user}"
```

parses correctly.

**Comment by blakerouse** [comment]
Fixed in #139
