### ISSUE TITLE
Prevent validation on custom structs for nil values

### ISSUE THREAD

**Issue by simitt** [elastic/go-ucfg#147]
According to https://github.com/elastic/go-ucfg/blob/master/validator.go#L213, the validation tag `nonzero` should only return an error if the configuration value is present but zero. 
For custom types this is not always the case at the moment.

Eg. have following custom type and configuration raises an error even if the `hosts` field is not present:
```
type urls []*url.URL

type MyConfig struct {
  Hosts urls `config:"hosts" validate:"nonzero"`
}
```

**Comment by urso** [comment]
Would it make sense to use `required` for your use-case?

**Comment by simitt** [comment]
Not really, the value is not required, but if given it is not allowed to be zero, basically exactly what I would expect from `nonzero`. 
We have a workaround by doing a manual validation for now, but this seems to have been introduced with one of the latest changes, as we used the tag on the custom type already.

**Comment by blakerouse** [comment]
@simitt You are correct, the issue is with the latest changes the `nonzero` is being called when the array is `nil`. Working on a fix so `nonzero` doesn't validate when the value is nil.
