### ISSUE TITLE
ucfg `Value` parses `.` in strings, breaking upstream Conditional statements in config

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/go-ucfg#196]
Right now, `ValueWithConfig` will parse a string like `startsWith(test, testthing)` as though it's an array, causing a parsing failure: `expected ',' when parsing 'startsWith('test', 'testthing')'`. This function-like format is used by conditional statements in filebeat logging config.

This breaks upstream `Unpack()` statements when the underlying config contains this string. 

I have no idea why this functionality is enabled by default, so I'm not sure what the best way to fix this is. I assume there's something that has to use this syntax, but I have no idea what. The `IgnoreCommas` setting in `ValueWithConfig` will fix this, although I'm not sure if this should be applied globally or based on some more limited set of conditions.

**Comment by cmacknz** [comment]
I think the important piece of context here is that when we encountered this `'startsWith('test', 'testthing')'` was a YAML key value. In this case the `,` should just be ignored.

As an arbitrary string without any kind of specification for what is valid, then as go-ucfg is written today I think trying to parse this as an array is correct as far as go-ucfg is implemented.

We need to constraint what go-ucfg is allowed to do in the context of YAML, ideally we'd just give it direct constraints like "parse this as YAML" or "parse this as JSON". Right now go-ucfg supports those as well as arbitrarily formatted environment variables and command line arguments.

**Comment by fearful-symmetry** [comment]
@cmacknz I agree, this is definitely an issue with us just not being able to turn off the string parsing.

I assume we can just add some `unpack()` option to pass  `IgnoreCommas` to the underlying parser.

**Comment by fearful-symmetry** [comment]
A bit of an update, the reason why we don't hit this more is that it requires the `VarExp`. This is used as a Default unpacking option at a few points in elastic-agent. Here's a basic reproduction:

```
func TestValueUnpack(t *testing.T) {
	extended := map[string]interface{}{
		"inputs": []interface{}{
			map[string]interface{}{
				"streams": []interface{}{
					map[string]interface{}{
						"condition": "startsWith('${host.name}','motmot')",
						"data_stream": map[string]interface{}{
							"dataset": "docker.container_logs",
						},
					},
				},
			},
		},
	}

	extendedCfg, err := NewFrom(extended, VarExp) // VarExp will trigger the bug
	require.NoError(t, err)

	var test map[string]interface{}
	err = extendedCfg.Unpack(&test, ResolveNOOP) // Error happens here
	require.NoError(t, err)
	t.Logf("got : %#v", test)

}
```
