### ISSUE TITLE
Syntax Error when trying to install a beat

### ISSUE THREAD

**Issue by bklise-goomzee** [elastic/go-ucfg#39]
On a Ubuntu 14.04 Linux server running `go1.5.2 linux/amd64` whenever I run `go install ...` for beats packages I get the following error:

~~~
$ go install
# github.com/elastic/go-ucfg
../../elastic/go-ucfg/variables.go:286: syntax error: argument to go/defer must be function call
~~~

On a whim, I edited the file and commented out the `defer` func and packages will install? What, if anything, am I doing wrong as I'd hate to comment out lines of your code to make this work.

**Comment by ruflin** [comment]
Beats requires at least Golang 1.6. Can you check if everything works fine with Golang 1.6?

**Comment by urso** [comment]
go-ucfg is tested automatically with 1.5.3, 1.6 and golang tip. Will check.

Anyway, beats uses vendoring and you should enable GOVENDOREXPERIMENT=1 when compiling with go1.5.x . With beats using go 1.6, it's recommended to compile with 1.6 anyways.

**Comment by urso** [comment]
checking source, syntax looks good to me. Plus, do not remove the defer. If parsing fails, you leaking a go-routine.

**Comment by bklise-goomzee** [comment]
Updated to go1.6.2, uncommented the code and everything seems to be working fine! Thanks for the help!
